# config/my_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # Define the controllers with the names you will use in the spawner
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

# Parameters for the 'diff_cont' controller
diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.35
    wheel_radius: 0.05
    publish_rate: 50.0
    use_stamped_vel: false

# Parameters for the 'joint_broad' controller
joint_broad:
  ros__parameters:
    {}